covMat = [1 0.5 0.25; 0.5 1 0.5; 0.25 0.5 1];

sqrtMat = chol(covMat, 'lower');

nSamples = 1e7;

whiteNoise = reshape(sqrt(1/2)*randn(nSamples * 3, 2) * [1 ;1i], [], 3);

noiseMult = transpose(sqrtMat * transpose(whiteNoise));

noise = gen_corr_complex_noise(covMat, nSamples);

disp('estimated covmat of noise generated by mvnrnd'); 
abs(noise' * noise / nSamples)
disp('estimated covmat of noise generated by matrix multiplication'); 
abs(noiseMult' * noiseMult / nSamples)
disp('true covmat')
covMat
